name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  audit:
    name: Audit
    runs-on: "ubuntu-latest"
    steps:
      - name: Audit Node dependencies
        run: npm audit --audit-level moderate
